name = "proxy-router"
main = "index.js"
compatibility_date = "2023-12-01"

# Cloudflare Pages 設定
[pages]
# 自訂網域設定
custom_domains = [
  "homershie.com",
  "www.homershie.com"
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



